"""base init

Revision ID: 0f271e752ed1
Revises:
Create Date: 2025-06-26 16:08:29.105231

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0f271e752ed1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
